Change gtag events to track dialog to purchase
diffus-me/Fooocus pull request #64
Opened 2024-02-01 14:04 UTC by BeEdward

2024-02-01 14:27 UTC, linjiX requested changes

2024-02-01 14:27 UTC, linjiX commented on templates/ui.html
> +              if (typeof callback === 'function') {
put callback in `finally` block?

2024-02-01 14:27 UTC, linjiX commented on templates/ui.html
> +          getItemsMapping(callback = null) {
this function is not be called?

2024-02-01 18:24 UTC, linjiX approved these changes

2024-02-01 20:12 UTC, linjiX requested changes

2024-02-01 20:12 UTC, linjiX commented on templates/ui.html
> +                return this.analyticsProductInfo.itemsMappingitemsMapping[key];
should `itemsMappingitemsMapping` be `itemsMapping`?

2024-02-01 20:12 UTC, linjiX commented on templates/ui.html
> +            const listUniqueId = this.getItemUniqueId(this.popup.URL) || this.popup.URL;
this code block to get `listUniqueId`, `domain` and `items` seems appears twice, should it be a function?

2024-02-02 02:46 UTC, linjiX approved these changes

2024-02-02 13:45 UTC, BeEdward commented
cherry-picked to diffus

2024-02-02 13:45 UTC, BeEdward commented
cherry-picked to diffus

2024-02-02 13:45 UTC, closed without merging